# Configuration file
# key = value
quarkus.http.host=0.0.0.0
quarkus.application.name=coffee-shop-client
quarkus.http.port=8001
quarkus.eureka.region=default
## configuration related to reaching the eureka servers
quarkus.eureka.prefer-same-zone=true
quarkus.eureka.should-use-dns=false
quarkus.eureka.service-url.default=http://localhost:8762/eureka